<?php

/**
 * @file
 * UMDDS Sidebar Menu module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function umdds_sidebar_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.umdds_sidebar':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

function umdds_theme_registry_alter(&$theme_registry) {
// dsm($theme_registry);
  // $theme_registry['umdds_sidebar_menu__main']['variables']['top_parent'] = [];
}

/**
 * Implements hook_theme().
 */
function umdds_sidebar_menu_theme($existing, $type, $theme, $path) {
  return [
    'umdds_sidebar_menu__main' => [
      'render element' => 'menu',
      'base hook' => 'menu',
      'variables' => [
        'menu_name' => '',
        'items' => [],
        'attributes' => [],
        'top_parent' => [],
      ],
    ],
  ];
}
